// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.Context;

namespace ProductAPI.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20210827072949_add-expirycolumn-updatevalues")]
    partial class addexpirycolumnupdatevalues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("BasePrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemainingDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("TodaysDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 1000.0,
                            CreatedDate = new DateTime(2021, 8, 25, 9, 29, 49, 427, DateTimeKind.Local).AddTicks(8870),
                            Description = "Classic style",
                            ExpiryDate = new DateTime(2021, 8, 30, 9, 29, 49, 430, DateTimeKind.Local).AddTicks(3397),
                            ImageUrl = "image/Cabinet.jpg",
                            IsSold = false,
                            ProductName = "Cabinet",
                            RemainingDays = 3,
                            TodaysDate = new DateTime(2021, 8, 27, 9, 29, 49, 430, DateTimeKind.Local).AddTicks(3932)
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 2000.0,
                            CreatedDate = new DateTime(2021, 8, 27, 9, 29, 49, 430, DateTimeKind.Local).AddTicks(4392),
                            Description = "Well maintained cycle",
                            ExpiryDate = new DateTime(2021, 9, 1, 9, 29, 49, 430, DateTimeKind.Local).AddTicks(4403),
                            ImageUrl = "image/Cycle.jpg",
                            IsSold = false,
                            ProductName = "Cycle",
                            RemainingDays = 5,
                            TodaysDate = new DateTime(2021, 8, 27, 9, 29, 49, 430, DateTimeKind.Local).AddTicks(4406)
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 150.0,
                            CreatedDate = new DateTime(2021, 8, 26, 9, 29, 49, 430, DateTimeKind.Local).AddTicks(4410),
                            Description = "Brio train",
                            ExpiryDate = new DateTime(2021, 8, 31, 9, 29, 49, 430, DateTimeKind.Local).AddTicks(4413),
                            ImageUrl = "image/Toys.jpg",
                            IsSold = false,
                            ProductName = "Toys",
                            RemainingDays = 4,
                            TodaysDate = new DateTime(2021, 8, 27, 9, 29, 49, 430, DateTimeKind.Local).AddTicks(4416)
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 5000.0,
                            CreatedDate = new DateTime(2021, 8, 23, 9, 29, 49, 430, DateTimeKind.Local).AddTicks(4419),
                            Description = "Super powerful garden maintainer",
                            ExpiryDate = new DateTime(2021, 8, 28, 9, 29, 49, 430, DateTimeKind.Local).AddTicks(4422),
                            ImageUrl = "image/GardenTools.jpg",
                            IsSold = false,
                            ProductName = "GardenTools",
                            RemainingDays = 1,
                            TodaysDate = new DateTime(2021, 8, 27, 9, 29, 49, 430, DateTimeKind.Local).AddTicks(4425)
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 200.0,
                            CreatedDate = new DateTime(2021, 8, 24, 9, 29, 49, 430, DateTimeKind.Local).AddTicks(4428),
                            Description = "Iron pan",
                            ExpiryDate = new DateTime(2021, 8, 29, 9, 29, 49, 430, DateTimeKind.Local).AddTicks(4430),
                            ImageUrl = "image/Vessel.jpg",
                            IsSold = false,
                            ProductName = "Vessel",
                            RemainingDays = 2,
                            TodaysDate = new DateTime(2021, 8, 27, 9, 29, 49, 430, DateTimeKind.Local).AddTicks(4432)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
