// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.Context;

namespace ProductAPI.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20210620060321_SeedDB")]
    partial class SeedDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("BasePrice")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemainingDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 1000.0,
                            Description = "Classic style",
                            ImageUrl = "image/Cabinet.jpg",
                            IsSold = false,
                            ProductName = "Cabinet",
                            RemainingDays = 3
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 2000.0,
                            Description = "Well maintained cycle",
                            ImageUrl = "image/Cycle.jpg",
                            IsSold = false,
                            ProductName = "Cycle",
                            RemainingDays = 1
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 150.0,
                            Description = "Brio train",
                            ImageUrl = "image/GardenTools.jpg",
                            IsSold = false,
                            ProductName = "Toys",
                            RemainingDays = 5
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 5000.0,
                            Description = "Super powerful garden maintainer",
                            ImageUrl = "image/Toys.jpg",
                            IsSold = false,
                            ProductName = "GardenTools",
                            RemainingDays = 2
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 200.0,
                            Description = "Iron pan",
                            ImageUrl = "image/Vessel.jpg",
                            IsSold = false,
                            ProductName = "Vessels",
                            RemainingDays = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
