// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.Context;

namespace ProductAPI.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20210816172134_add-datefieldcolumns")]
    partial class adddatefieldcolumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("BasePrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemainingDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("TodaysDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 1000.0,
                            CreatedDate = new DateTime(2021, 8, 14, 19, 21, 33, 754, DateTimeKind.Local).AddTicks(501),
                            Description = "Classic style",
                            ImageUrl = "image/Cabinet.jpg",
                            IsSold = false,
                            ProductName = "Cabinet",
                            RemainingDays = 3,
                            TodaysDate = new DateTime(2021, 8, 16, 19, 21, 33, 756, DateTimeKind.Local).AddTicks(3358)
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 2000.0,
                            CreatedDate = new DateTime(2021, 8, 16, 19, 21, 33, 756, DateTimeKind.Local).AddTicks(3839),
                            Description = "Well maintained cycle",
                            ImageUrl = "image/Cycle.jpg",
                            IsSold = false,
                            ProductName = "Cycle",
                            RemainingDays = 1,
                            TodaysDate = new DateTime(2021, 8, 16, 19, 21, 33, 756, DateTimeKind.Local).AddTicks(3852)
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 150.0,
                            CreatedDate = new DateTime(2021, 8, 12, 19, 21, 33, 756, DateTimeKind.Local).AddTicks(3856),
                            Description = "Brio train",
                            ImageUrl = "image/Toys.jpg",
                            IsSold = false,
                            ProductName = "Toys",
                            RemainingDays = 5,
                            TodaysDate = new DateTime(2021, 8, 16, 19, 21, 33, 756, DateTimeKind.Local).AddTicks(3859)
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 5000.0,
                            CreatedDate = new DateTime(2021, 8, 15, 19, 21, 33, 756, DateTimeKind.Local).AddTicks(3862),
                            Description = "Super powerful garden maintainer",
                            ImageUrl = "image/GardenTools.jpg",
                            IsSold = false,
                            ProductName = "GardenTools",
                            RemainingDays = 2,
                            TodaysDate = new DateTime(2021, 8, 16, 19, 21, 33, 756, DateTimeKind.Local).AddTicks(3865)
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 200.0,
                            CreatedDate = new DateTime(2021, 8, 14, 19, 21, 33, 756, DateTimeKind.Local).AddTicks(3867),
                            Description = "Iron pan",
                            ImageUrl = "image/Vessel.jpg",
                            IsSold = false,
                            ProductName = "Vessel",
                            RemainingDays = 3,
                            TodaysDate = new DateTime(2021, 8, 16, 19, 21, 33, 756, DateTimeKind.Local).AddTicks(3870)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
